// SPDX-License-Identifier: MPL-2.0

pragma solidity ^0.8.13;

import "@divergencetech/ethier/contracts/utils/DynamicBuffer.sol";

import "./BufferUtils.sol";
import "./ICrypToadzCustomAnimations.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////
// This contract was auto-generated by a tool, and may be overwritten. Do not make changes to this file. //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

contract CrypToadzCustomAnimations is ICrypToadzCustomAnimations {

    mapping(uint256 => mapping(uint8 => uint16)) customAnimationLengths;
    mapping(uint256 => mapping(uint8 => address)) customAnimationData;

    function isCustomAnimation(uint tokenId) external view returns (bool) {
        return customAnimationData[tokenId][0] != address(0);
    }

    function getCustomAnimation(uint256 tokenId)
        external
        view
        returns (bytes memory buffer)
    {
        uint256 size;
        uint8 count;
        while (customAnimationLengths[tokenId][count] != 0) {
            size += customAnimationLengths[tokenId][count++];
        }

        buffer = DynamicBuffer.allocate(size);
        for (uint8 i = 0; i < count; i++) {
            bytes memory chunk = BufferUtils.decompress(
                customAnimationData[tokenId][i],
                customAnimationLengths[tokenId][i]
            );
            DynamicBuffer.appendUnchecked(buffer, chunk);
        }
    }

    constructor() {

    }
}